[package]

name = "sequence_trie"
version = "0.0.10"
description = "Trie-like data-structure for storing sequences of values."

license = "GPL-3.0+"
authors = ["Michael Sproul <micsproul@gmail.com>"]

documentation = "https://michaelsproul.github.io/rust_sequence_trie/"
repository = "https://github.com/michaelsproul/rust_sequence_trie"

keywords = ["trie", "tree", "hash", "data-structure", "collection"]

[lib]

name = "sequence_trie"
