[package]

name = "sequence_trie"
version = "0.0.9"

authors = ["Michael Sproul <micsproul@gmail.com>"]

description = "Trie-like data-structure for storing sequences of values."
documentation = "http://sproul.io/rust/sequence_trie/"
repository = "https://github.com/michaelsproul/rust_sequence_trie"
readme = "README.md"
keywords = ["trie", "tree", "hash", "data-structure", "collection"]
license = "GPL-3.0+"

[lib]

name = "sequence_trie"
